### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by thejsa** [RiiConnect24/Recommended-Sites-EU#1]
We could do with a README with more than just the project name.

**Comment by spotlightishere** [comment]
I think this should be merged with https://github.com/RiiConnect24/Recommended-Sites-US if I'm understanding the purpose correctly. @larsenv, any opinions?

**Comment by pulkonet** [comment]
@thejsa Can I do this?

**Comment by spotlightishere** [comment]
Sorry @pulkonet, @thejsa went to go do other things 😅 

Looks like this was merged in #2, so all's good. Thanks for offering!
