### ISSUE TITLE
Page not found 

### ISSUE THREAD

**Issue by Jake801** [RiiConnect24/Recommended-Sites-EU#3]
When going on to the recommended sites on the internet channel it says 'Not found the requested URL/wiilinks/was not found on this server.  Apache/2.4.25 (Debain) Server at ms.nintendo-europe.com Port 80'.

**Comment by larsenv** [comment]
We have moved the bookmarks to https://bookmark.rc24.xyz/. Please try going on it again, as I have moved it so it should load properly now.

**Comment by Jake801** [comment]
ok it works now thx Larsen :) nice to see something new on the internet channel.
